site_name: Realms Playerlist Bot
site_description: "A bot that helps out owners of Minecraft: Bedrock Edition Realms by showing various statistics related to player join/leaves."
site_url: https://playerlist.astrea.cc
theme:
  name: material
  custom_dir: overrides
  logo: _static/rpl_symbol_white.png
  favicon: _static/rpl_favicon.ico

  icon:
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: purple
      accent: purple
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: purple
      accent: purple
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - toc.follow
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - announce.dismiss

extra_css:
  - _static/custom.css

repo_url: https://github.com/AstreaTSS/RealmsPlayerlistBot
repo_name: AstreaTSS/RealmsPlayerlistBot

copyright: "&copy Copyright 2020-2024 AstreaTSS."
extra:
  social:
    - icon: fontawesome/solid/cookie
      link: "#__consent"
      name: Change Cookie Settings
    - icon: custom/topgg
      link: https://top.gg/bot/725483868777611275
      name: Top.gg Page
    - icon: fontawesome/brands/discord
      link: https://discord.gg/NSdetwGjpK
      name: Support Server
    - icon: simple/kofi
      link: https://ko-fi.com/astreatss
      name: Ko-Fi Page
    - icon: fontawesome/brands/github
      link: https://github.com/AstreaTSS/RealmsPlayerlistWebsite
      name: Website Source
    
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: umami
    url: !ENV UMAMI_SCRIPT_URL
    property: !ENV UMAMI_WEBSITE_ID

plugins:
  - search
  - offline
  - custom-privacy:
      assets_exclude:
        - https://giscus.app/*
  - custom-cards:
      cards_layout_options:
        background_color: "#b05bff1E"
        background_image: _static/social_card_bg.png
  - microsoft-verify:
      id: !ENV [MICROSOFT_APPLICATION_ID, ""]
  - autorefs
  - autolinks
  - awesome-pages
  - blog:
      blog_dir: updates
      archive: false
      categories: false
      draft_if_future_date: true
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      css_files:
        - _static/custom.css

markdown_extensions:
  - admonition
  - md_in_html
  - abbr
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - mdx_breakless_lists
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
