name: "Pages Build"
on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Compress Images
      id: calibre
      uses: calibreapp/image-actions@main
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        compressOnly: true

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: 'pip'
        cache-dependency-path: '**/requirements*.txt'

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build the sphinx documentation
      uses: rickstaa/sphinx-action@master
      with:
        docs-folder: "./docs"

    - name: HTML/CSS/JS Minifier
      uses: docker://devatherock/minify-js:1.0.3
      with:
        directory: "docs"
        add_suffix: false

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: rpl
        directory: docs/_build/html
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
